export const tools = {
  heading: { icon: 'title' },
  fontName: { icon: 'format_color_text' },
  fontSize: { icon: 'format_size' },
  foreColor: { icon: 'format_color_fill' },
  backColor: { icon: 'font_download' },
  bold: { icon: 'format_bold' },
  italic: { icon: 'format_italic' },
  strikeThrough: { icon: 'format_strikethrough' },
  underline: { icon: 'format_underlined' },
  // subscript: { icon: '' },
  // superscript: { icon: '' },
  createLink: { icon: 'link' },
  unlink: { icon: 'link_off' },
  justifyFull: { icon: 'format_align_justify' },
  justifyCenter: { icon: 'format_align_center' },
  justifyLeft: { icon: 'format_align_left' },
  justifyRight: { icon: 'format_align_right' },
  indent: { icon: 'format_indent_increase' },
  outdent: { icon: 'format_indent_decrease' },
  insertImage: { icon: 'insert_photo' },
  insertOrderedList: { icon: 'format_list_numbered' },
  insertUnorderedList: { icon: 'format_list_bulleted' },
  formatBlock: { icon: 'format_quote' },
  redo: { icon: 'redo' },
  undo: { icon: 'undo' }
};
